### ISSUE TITLE
Missing "entity_df_timestamp_range" argument, when executing "get_historical_features" command

### ISSUE THREAD

**Issue by KrzysztofNawrocki** [nossrannug/feast-postgres#11]
Hi,

I was just going through the basic "Quickstart" Feast tutorial (on Feast 0.17 version). I have changed is the feature_store.yaml to take advantage of the PostgreSQL plugin:

![image](https://user-images.githubusercontent.com/47433542/152368949-4567b9c0-9dc1-4cfb-8482-addb6a0a84cb.png)

(I don't need an online store for my project. This issue is however independent on that.)

I have created the registry, stores, the infastructure has been deployed.
However, when I executed the code for training_df creation I obtained such mistake:

![image](https://user-images.githubusercontent.com/47433542/152368571-1c650349-9575-46f9-9743-964792250712.png)

My feast-postgres version is 0.2.4.

Regards
Krzysztof

**Comment by KrzysztofNawrocki** [comment]
Thanks for such quick response, looking forward to it.

**Comment by coalindiax** [comment]
in new version of feast they have introduce this variable "entity_df_timestamp_range" either you can  downgrade feast version to 16.0 or wait for  update

**Comment by nossrannug** [comment]
Sorry for the slow response. I am working on upgrading feast-postgres to support feast 0.18.0 [here](https://github.com/nossrannug/feast-postgres/tree/upgrade-to-feast-0-18-0). But since I'm only able to work on this in my free time it happens slowly.
I've been in contact with the people at Tecton/Feast and we plan on getting the feast-postgres plugin merged into the main repo after I get it working with 0.18.0.

**Comment by nossrannug** [comment]
Sorry how long this has taken. I've updated feast-postgres to work with the next version of Feast. version 0.18.1 has a bug that causes feast-postgres to not work. I created a fix for it and that has been merged into the Feast repo so will hopefully get included in the next release of Feast.

**Comment by nossrannug** [comment]
Finally I've pushed 0.2.5 which should work with Feast 0.19.3 🎉
Can you please try it out and let me know if there are any issues.
