### ISSUE TITLE
Can't instantiate abstract class PostgreSQLOfflineStore

### ISSUE THREAD

**Issue by KrzysztofNawrocki** [nossrannug/feast-postgres#13]
Hi again, @nossrannug 

I have upgraded Feast to 0.18 version and at the moment I'm not only not able to create the dataset, i can't even execute _feast apply_...
After initialization of the repo, when I try to run _feast apply_ I get the following message:

![image](https://user-images.githubusercontent.com/47433542/152981114-59f89de1-4d93-42ff-947d-61a2af60cecb.png)

Summing up - the environment is:
Feast 0.18
Feast-postgres 0.2.4

![image](https://user-images.githubusercontent.com/47433542/152981238-b2f0c2bf-da52-4ab2-b088-a9ddb6401e3e.png)

**Comment by jungyuneum** [comment]
Hi,
Try downgrading feast to 0.17 for this to work.
Or you can add pull_all_from_table_or_query method under PostgreSQLOfflineStore class in postgres.py.

**Comment by cpatrickalves** [comment]
Hi there, 

Thanks for all your effort to build this plugin to feast.
In my case, I need feast version 0.18 because I am using the [local feature server.](https://docs.feast.dev/reference/feature-servers/local-feature-server)

Any idea how can this issue could be solved?

**Comment by nossrannug** [comment]
Hi @cpatrickalves,
I'm currently trying to get feast-postgres working with 0.18.0. It's taking more time than I had hoped but is getting very close. Only a few tests are failing which I hope that I'll be able to address in the next few days.

**Comment by cpatrickalves** [comment]
Thanks for the update @nossrannug

**Comment by nossrannug** [comment]
Sorry how long this has taken. I've updated feast-postgres to work with the next version of Feast. version 0.18.1 has a bug that causes feast-postgres to not work. I created a fix for it and that has been merged into the Feast repo so will hopefully get included in the next release of Feast.

**Comment by nossrannug** [comment]
Finally I've pushed 0.2.5 which should work with Feast 0.19.3 🎉
Can you please try it out and let me know if there are any issues.

**Comment by bgalvao** [comment]
> Finally I've pushed 0.2.5 which should work with Feast 0.19.3

I am testing these exact versions by running the Quickstart guide from Feast, Step 4: Generating training data.. There seems to be a bug upon running `get_historical_features`:

```python
store = FeatureStore(repo_path="./working_clam")
training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
    ],
).to_df()
```

which lands in the final error

```
UndefinedTable: relation "none" does not exist
LINE 65:     FROM None AS sub
```
