### ISSUE TITLE
I can't materalize data to Online Store

### ISSUE THREAD

**Issue by enveryildirim** [nossrannug/feast-postgres#14]
![image](https://user-images.githubusercontent.com/16373804/153480771-75fde304-7b0d-4356-bb72-c2b53bfcd18f.png)
![image](https://user-images.githubusercontent.com/16373804/153480832-64f18a8b-407d-473f-b3e3-13ab9e339b5b.png)
![image](https://user-images.githubusercontent.com/16373804/153481827-f7b11c9d-a3c0-4934-978d-5425fd5f3bb2.png)

feature_store.yaml
`

> project: feature_repo
> registry: data/registry.db
> provider: local
> online_store:
>     type: feast_postgres.PostgreSQLOnlineStore # MUST be this value
>     host: localhost
>     port: 5432                  # Optional, default is 5432
>     database: feast-tempdata
>     db_schema: feature_store    # Optional, default is None
>     user: feast-user
>     password: feast123456789
> offline_store:
>   type: file

`

**Comment by nossrannug** [comment]
Hey @enveryildirim,
Thanks for reporting the issue. I'm currently working on getting feast-postgres to work with the latest version of Feast. For now you can downgrade Feast to 0.15.1 (maybe 0.16.0 also works).

**Comment by nossrannug** [comment]
Sorry how long this has taken. I've updated feast-postgres to work with the next version of Feast. version 0.18.1 has a bug that causes feast-postgres to not work. I created a fix for it and that has been merged into the Feast repo so will hopefully get included in the next release of Feast.

**Comment by enveryildirim** [comment]
Thank You. @nossrannug

**Comment by nossrannug** [comment]
Finally I've pushed 0.2.5 which should work with Feast 0.19.3 🎉 
Can you please try it out and let me know if there are any issues.
