### ISSUE TITLE
postgresql version support

### ISSUE THREAD

**Issue by cheungsuifai** [nossrannug/feast-postgres#15]
which version of postgresql is support by feast-postgres currently?

I use **greenplum** as the online store, and get the below  error message after executing "feast apply":

psycopg2.errors.SyntaxError: syntax error at or near "NOT"
LINE 11:                         CREATE INDEX IF NOT EXISTS "digithin...

And here is the version info of command show version():
**PostgreSQL 9.4.24 (Greenplum Database 6.5.0 build commit:27520b0e901cefe748684c02e5155fb015cd5cc2) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 18 2020 23:07:19**

**Comment by cheungsuifai** [comment]
i've found such information about the index definition feature via https://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist :

Postgres 9.5 or newer
Now available:

CREATE INDEX IF NOT EXISTS ...

So from the point of view, only Postgres 9.5 or newer is supported.

**Comment by nossrannug** [comment]
I've only used 9.6 and newer when developing and testing. I'll add that to the readme

**Comment by cheungsuifai** [comment]
> I've only used 9.6 and newer when developing and testing. I'll add that to the readme

thank you for the reply.
my problem is solved.
