### ISSUE TITLE
create_saved_dataset(), RetrievalJob must contains metadata.

### ISSUE THREAD

**Issue by zilto** [nossrannug/feast-postgres#19]
I am building a system using the new **Feast** feature to create "static dataset" via the `FeatureStore` method `get_saved_dataset()`. I also use the feast-postgres extension for the registry, offline and online stores. Versions: feast==0.19.3,  feast-postgres==0.2.5

I currently receive the error:

> \site-packages\feast\feature_store.py in create_saved_dataset(self, from_, name, storage, tags, feature_service)
             if not from_.metadata:
-->             raise ValueError(
"RetrievalJob must contains metadata. "
"Use RetrievalJob produced by get_historical_features"

After investigating, it seems that the class `PostgresSQLOfflineStore` found in `/feast_postgres/offline_stores/postgres.py` does not return `PostgreSQLRetrievalJob` with a `._metadata` attribute. This leads to `get_saved_dataset()` raising the exception.

Hope this helps!

**Comment by nossrannug** [comment]
Hey @zilto ,
Thank you for creating this issue. I'm currently trying to get feast-postgres merged into Feast https://github.com/feast-dev/feast/pull/2401
We can look into adding this functionality once it is a part of Feast.

**Comment by zilto** [comment]
As a note, I looked more into it, and the issue has deeper roots.

To create a SavedDataset, the PostgreSQLRetrievalJob need to have the `persist` method implemented. Sadly, the protocol buffers schema for `SavedDatasetStorage` currently does not provide an interface for custom RetrievalJob or OfflineStore.
