### ISSUE TITLE
FeatureStore.get_historical_features() fails on SQL string for entity_df

### ISSUE THREAD

**Issue by vtslab** [nossrannug/feast-postgres#3]
Thanks for providing this git repository. It seems interesting as on premise solution when workloads do not fit in memory.  

While FeatureStore.get_historical_features() worked OK on providing a true entity_df it failed on providing an SQL string as entity_df:  
psycopg2.errors.SyntaxError: syntax error at or near "'SELECT event_timestamp, driver_id FROM driver_hourly_stats'"  
LINE 2: ...t_entity_df_1f1e704d441240dbb9fb86be65a21f30" AS ('SELECT ev...  

When checking in feast_postgres.utils.sql_to_postgres_table() it shows that this code cannot possibly work because the query string is inserted as a literal. Even after correcting this, other issues appear downstream, so I guess this usage scenario has not been tested yet.

**Comment by vtslab** [comment]
Hi @nossrannug, when I fixed the CREATE TABLE, the script just hung after having created the temporary table (checked this with psql from the command line). I stopped debugging when I saw that utils.df_to_postgres_table returns a pandas.DataFrame instead of a Dict[str, str], see [https://github.com/nossrannug/feast-postgres/blob/02bf428ab89521758af41f02bbe2ccf757e1edc4/feast_postgres/utils.py#L38.](https://github.com/nossrannug/feast-postgres/blob/02bf428ab89521758af41f02bbe2ccf757e1edc4/feast_postgres/utils.py#L38).  
Regarding your other question, I think it is less complex/errorprone to maintain the temp table, because you also have to create the temp table when a pandas dataframe is provided instead of an SQL query.

**Comment by nossrannug** [comment]
I think the issue has been resolved in [v0.1.5](https://pypi.org/project/feast-postgres/0.1.5/). 

I ended up using the query rather than creating a tmp table when entity_df is a SQL string.

**Comment by vtslab** [comment]
Chill, that was fast! The historical features work now for:
SELECT event_timestamp, driver_id FROM driver_hourly_stats WHERE event_timestamp > '2021-01-23'
So, the current ticket can be closed.

I can still make my script hang for a different or missing WHERE clause, but I first have to find out whether that is an issue in feast-postgres or in feast. I will make a new ticket for that.
