### ISSUE TITLE
Poor query performance in Postgres 14.1

### ISSUE THREAD

**Issue by mrkl1akza13** [nossrannug/feast-postgres#5]
I'm running a Postgres 14.1 locally. In the Postgres DB there is one table `driver_stats` with **1000** rows that I want to use as a data source. 

The data source definition is:
```
driver_hourly_stats = PostgreSQLSource(
    query="SELECT * FROM driver_stats",
    event_timestamp_column="event_timestamp",
    created_timestamp_column="created",
)
```
I create a FeatureView in the following way:
```
driver_hourly_stats_view = FeatureView(
    name="driver_hourly_stats_postgres_trunc",
    entities=["driver_id"],
    ttl=Duration(seconds=86400 * 1),
    features=[
        Feature(name="conv_rate", dtype=ValueType.FLOAT),
        Feature(name="acc_rate", dtype=ValueType.FLOAT),
        Feature(name="avg_daily_trips", dtype=ValueType.INT64),
    ],
    online=True,
    batch_source=driver_hourly_stats,
    tags={},
)
```

Then, fetching all records with the following:
```
training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "driver_hourly_stats_postgres_trunc:conv_rate",
        "driver_hourly_stats_postgres_trunc:acc_rate",
        "driver_hourly_stats_postgres_trunc:avg_daily_trips",
    ],
).to_df()
```

finishes in ~55 seconds. Is such performance expected? Are there any ways to optimize for tables with 100k records?

**Comment by nossrannug** [comment]
Hey @kirill-zaitsev, thanks for opening the issue.
I have tested postgres 14 where I have two tables that each contains over 9 mill rows. When I fetch historical features for 100 entities, and get values from both tables, it took less than 1 sec.
I will double-check today or tomorrow and get back to you.

**Comment by nossrannug** [comment]
Well.. this has now been confirmed to be very slow.
The reason is the `ttl`. Changing the `ttl` from 84600 to 1000 makes the query a lot faster. You have to run feast apply after changing the value if you want to test it.

I'll need to spend some time digging into this to figure out if and how to address this. Maybe the issue is with the example setting the `ttl` to 1 day when the features are calculated once every hour (The `driver_stats` table has a row for each hour).

**Comment by kirill-zaitsev** [comment]
I confirm both of your points. 
Reducing ttl to a value that prevents overlaps between event_timestamps (<=1 hour) results in runtime ~0.8s. 
Reducing versatility in event_timestamps results in a gradual query speedup, ultimately to ~0.3s when the whole event_timestamp column has a single value.
