### ISSUE TITLE
Support a db user that does not have a create schema privilege

### ISSUE THREAD

**Issue by benny-hal** [nossrannug/feast-postgres#7]
I tried using this repo, it seemed just what we needed. However, I got stuck that the DB user I was granted does not have the create schema privilege. It would of useful if this repo does not require that privilege

**Comment by nossrannug** [comment]
Hey @benny-hal ,
Is it only the schema that the user can't create? The user would still need to have the privilege to create tables and indexes.

**Comment by benny-hal** [comment]
correct, just the schema

**Comment by nossrannug** [comment]
@benny-hal , I just published v0.2.1 (https://pypi.org/project/feast-postgres/) where the registry and the online store check if the schema exists before trying to create it. Could you please let me know if you'll be able to test it and then let me know if it worked for you?

**Comment by benny-hal** [comment]
Awesome! Will check soon, thx!

**Comment by benny-hal** [comment]
@nossrannug yes it works and the publish also made the `PostgreSQLRegistryStore` available in pip
I am using both...
thx!
