### ISSUE TITLE
would caching make sense?

### ISSUE THREAD

**Issue by benny-hal** [nossrannug/feast-postgres#9]
Hi @nossrannug , me again...

Would it make sense for `get_registry_proto` of ` PostgreSQLRegistryStore` to return a cached copy of the `registry_proto` instead of quering for it each time? (`update_registry_proto` would clear the cache) 

Perhaps doing this could be an option in the `RegistryConfig`?

**Comment by nossrannug** [comment]
Hey @benny-hal,
The caching is handled by [registry.py](https://github.com/feast-dev/feast/blob/54d0f3a1842c7613aaffcd67512e08ab9b688740/sdk/python/feast/registry.py#L737) in Feast, so when the `get_registry_proto` method is called, it expects the registry to be fetched.

**Comment by benny-hal** [comment]
thx, will take a look, but the bottom line is too many requests are going to the DB to get the registry. It would be good if I could control that some more. Will think about it...
